[build]
  base = "/"
  publish = "/client/build/"
  command  = "npm run build"
  functions = "functions/"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/stateless_server/:splat"
  status = 200
